#!/usr/bin/env bash
#Write a Bash script that displays numbers from 1 to 100.
#Displays FizzBuzz when the number is a multiple of 3 and 5
#Displays Fizz when the number is multiple of 3
#Displays Buzz when the number is a multiple of 5

cont=1
while [ $cont -le 100 ];
do
if [ $((cont%15)) == 0 ] 
then
    echo "FizzBuzz"
elif [ $((cont%3)) == 0 ]
then
    echo "Fizz"
elif [ $((cont%5)) == 0 ]
then
    echo "Buzz"
else
    echo $cont
fi
    cont=$(( cont + 1 ))
done
