#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

cont=1
while [ $cont -le 10 ]
do
    echo "Best School"
if [[ $cont -eq 10 ]]; then
    echo "Hi"
    fi
    cont=$(( cont + 1 ))
done
