#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
cont=1
while [[ $cont -le 10 ]]
do
if [[ $cont -eq 4 ]]; then
    echo "bad luck"
elif [[ $cont -eq 8 ]]; then
    echo "good luck"
else
    echo "Best School"
    fi
    cont=$(( cont + 1 ))
done
