#!/usr/bin/env bash
#Write a Bash script that displays the time for 12 hours and 59 minutes

hour=0
min=1
while [ $hour -le 12 ];
do    
    echo "Hour: ${hour}"
while [ $min -lt 60 ];
do
    echo $min
    let min+=1
done
    let min=1 
    let hour+=1
done
