#!/usr/bin/env bash
#Write a Bash script that gives you information about the school file.(if, else)

File=school
if [ -e $File ];
then    
    echo "$File school file exists"
    if [ -s $File ];
    then
	echo "$File school file is not empty"
    else
	echo "$File school file is empty"
    fi
    if [ -f $File ];
    then	
	echo "$File school is a regular file"
    fi
else
    echo "$File school file does not exist"
fi
